pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'Obteniendo código del repositorio...'
            }
        }

        stage('Build') {
            steps {
                echo 'Compilando proyecto Maven...'
                bat 'mvn clean compile'
            }
        }

        stage('Unit Tests') {
            steps {
                echo 'Ejecutando pruebas unitarias...'
                bat 'mvn test'
            }
        }

        stage('Integration Tests') {
            steps {
                echo 'Ejecutando pruebas de integración...'
                bat 'mvn verify'
            }
        }

    }

    post {

        success {
            echo 'Pipeline ejecutado exitosamente'
        }

        failure {
            echo 'Pipeline con errores'
        }
    }
}